### ISSUE TITLE
debugging guidance

### ISSUE THREAD

**Issue by arup-yun** [speckleworks/SpeckleExcel#12]
Need guidance on client side debugging at runtime for desktop excel plugin. Is there a way to set it up in visual studio?

**Comment by mishaelnuh** [comment]
Hi!

You should be able to debug it using VS Code. There’s a guide to attaching an external debugger here: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/test-debug-office-add-ins.

**Comment by mishaelnuh** [comment]
Found a more comprehensive guide here specific to VScode and node.js: https://code.visualstudio.com/docs/nodejs/nodejs-debugging

**Comment by arup-yun** [comment]
Many thanks!
